//查询未审核经纪人信息
export const POST_UNCHECK_AGENT_SUCCESS = 'POST_UNCHECK_AGENT_SUCCESS'
export const POST_UNCHECK_AGENT_FAIL = 'POST_UNCHECK_AGENT_FAIL'
//经纪人列表
export const POST_AGENT_LIST_SUCCESS = 'POST_AGENT_LIST_SUCCESS'
export const POST_AGENT_LIST_FAIL = 'POST_AGENT_LIST_FAIL'
//用户列表
export const POST_USER_LIST_SUCCESS = 'POST_USER_LIST_SUCCESS'
export const POST_USER_LIST_FAIL = 'POST_USER_LIST_FAIL'
//未审核House列表
export const POST_UNCHECK_HOUSE_LIST_SUCCESS = 'POST_UNCHECK_HOUSE_LIST_SUCCESS'
export const POST_UNCHECK_HOUSE_LIST_FAIL = 'POST_UNCHECK_HOUSE_LIST_FAIL'
//House列表
export const POST_HOUSE_LIST_SUCCESS = 'POST_HOUSE_LIST_SUCCESS'
export const POST_HOUSE_LIST_FAIL = 'POST_HOUSE_LIST_FAIL'
